name: Release DRBD9 Images

on:
  push:
    branches: [ "main" ]
    paths:
    - 'docker-drbd9/**'
    - "helm/drbd-adapter/Chart.yaml"
    - '.github/workflow/release-drbd9-images.yml'

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: all

    - name: Available platforms
      run: echo ${{ steps.qemu.outputs.platforms }}

    - name: Configure Docker
      run: |
        sudo cp -vf docker_daemon.json /etc/docker/daemon.json
        sudo systemctl restart docker

    - name: Build official DRBD9 images
      run: make drbd9 REG=ghcr.io/$( echo ${{ github.repository_owner }} | tr 'A-Z' 'a-z' )

    - name: Login registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Push images
      run: |
        make push REG=ghcr.io/$( echo ${{ github.repository_owner }} | tr 'A-Z' 'a-z' ) IMG="rhel7 rhel8 rhel9 bionic focal jammy kylin10"